site_name: Blitz Trader
site_description: Blitz Trading Platform API, SDK and Broker Integration Documentation
site_author: Blitz Trader
site_url: https://your-domain.com

repo_name: Blitz Trader
#repo_url: https://github.com/your-org/blitz-docs

theme:
  name: material
  logo: assets/icon.png
  favicon: assets/favicon.ico
  font:
    text: Outfit
    code: Fira Code

  features:
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - navigation.instant
    - toc.follow
    - content.code.copy
    - search.highlight
    - search.suggest

  palette:
    # Dark Mode (Default)
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Light Mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji

extra_css:
  - css/custom.css

copyright: "© Blitz"

nav:
  - Introduction: index.md
  - Quick Start: overview.md

  # User setup

  - User Setup:
    - Create Account: userSetup/createAccount.md
    - Forgot Password: userSetup/forgotPassword.md
    - Generate API Key: userSetup/generateKey.md
  # ---------------------------------------------------
  # API REFERENCE
  # ---------------------------------------------------

  - API Reference:
      - API Structure: api/API_Structure.md
      - Authentication: api/authentication.md

      - Trading APIs:
          - Orders: api/trading/orders.md
          - Positions: api/trading/position.md
          # - Statistics: api/trading/statistics.md
          - Trades History: api/trading/trades.md
          - Signals: api/trading/signals.md
          

      - Market Data APIs:
          - Download Instruments: api/market-data/downloadInstrument.md
          - Instrument Detail: api/market-data/instrumentDetail.md
          - Last Trading Price: api/market-data/ltp.md
          - Option Chain: api/market-data/optionchain.md
          - Market Quote: api/market-data/marketquote.md
          - Historical Data: api/market-data/historicaldata.md

  # ---------------------------------------------------
  # SDK
  # ---------------------------------------------------

  - Blitz SDK:
      - What is SDK: sdk/about_sdk.md
      - Get Started with SDK: sdk/sdk.md
      - Authentication: sdk/authentication.md
      - Interactive Server SDK: sdk/interactiveServerSdk.md
      - Market Data SDK: sdk/marketdatasdk.md
      - Instrument Master: sdk/instrumentmasterskd.md

  # ---------------------------------------------------
  # TPOMS
  # ---------------------------------------------------

  - TPOMS:
      - Overview: tpoms/overview.md
      - Order Request: tpoms/blitz_order_request.md

      - Broker Integrations:
          - Zerodha: tpoms/brokers/zerodha.md
          - Motilal: tpoms/brokers/motilal.md
